### ISSUE TITLE
Videos can be processed in sequential instead of exhaustive mode 

### ISSUE THREAD

**Issue by zbuhrer** [zbuhrer/pointcloud_converter#1]
It's faster!

**Comment by zbuhrer** [comment]
Confirmed. It is faster, lol

**Comment by Cozyuvi** [comment]
hello sir ,
i am a student from india who is current doing studies in diploma computer science.
i was eagerly invested in your "pointer cloud" project and was trying to set up the project in my laptop .
but currently i am facing some issues regarding the colmap and also encountering some error also so 
can you please make a video over how i can set up your whole project in pc if possible 
i will be really thankfull to you ,
yuvi thakur
